# Generated by Django 5.0.4 on 2024-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_delete_unavailabledate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='johnsmith@gmail.com', max_length=200),
        ),
    ]
