# Generated by Django 5.0.4 on 2024-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='insurance',
            field=models.CharField(choices=[('basic', 'Basic'), ('full', 'Full')], default='basic', max_length=10),
        ),
    ]
